name: "AA105: IDS Seminar I"
author: Michael Collins
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "lax_spacing"]
baseurl: /aa105-fa18--oer
permalink: pretty
markdown: kramdown
timezone: America/New_York
future: true
plugins:
  - jekyll-sitemap
# Github links
github-repo: https://github.com/michael-collins/aa105-fa18--oer
#directoy config ########################################
#
# CANVAS COURSE NUMBER
# Example Num: https://psu.instructure.com/courses/#######/users
# _______________________________________________^
# {{site.canvas-base}}{{site.canvas-num}}/users
canvas-num: 1913414
canvas-base: https://psu.instructure.com/courses/
#
#
#collections_dir: all_collections
collections:
  agenda:
    output: true
    permalink: /agenda/:title.html
  lessons:
    output: true
    permalink: /lessons/:title.html
  exercises:
    output: true
    permalink: /exercises/:title.html
  projects:
    output: true
    permalink: /projects/:title.html
  grading:
    output: true
    permalink: /grading/:title.html
  syllabus:
    output: true
    permalink: /syllabus/:title.html
  topics:
    output: true
    permalink: /topics/:title.html
#exercises ########################################
assignments:
  exercise-1:
    due-date: 2:30pm on August 31, 2018
    dropbox-url: https://psu.instructure.com/courses/1913414/assignments/10348435
    title: Exercise 1
    doc: /exercises/design-research.html
  exercise-2:
    due-date: 2:30pm on Sept 7, 2018
    due-date-iso: '2018-09-07T06:30:00+00:00'
    dropbox-url: https://psu.instructure.com/courses/1913414/assignments/10361857
    title: Exercise 2
    doc: /exercises/fix-it-pitch.html
  project-1:
    doc: /projects/2d-poster-project.html
    due-date: 2:30pm on Sept 14, 2018
    due-date-iso: '2018-09-21T06:30:00+00:00'
    dropbox-url: https://psu.instructure.com/courses/1913414/assignments/10347035
    title: Project 1
    
  
  # - exercise: maya-modeling-image-planes
  #   title: Intro to Modeling in Maya
  #   subtitle: testing config
  #   submission_link: 
  #   comments_enabled:
  #   published: true
  #   assigned: 1/14/2016
  #   due: 1/19/2016
  # - exercise: maya-texturing-objects
  #   title: Intro to Texturing in Maya
  #   subtitle: testing config
  #   submission_link: 
  #   comments_enabled:
  #   published: true
  #   assigned: 1/19/2016
  #   due: 1/21/2016
  # - exercise: maya-animation-animating
  #   title: Animating in Maya
  #   subtitle:
  #   submission_link: 
  #   comments_enabled:
  #   published: true
  #   assigned: 1/26/2016
  #   due: 1/28/2016
#topics  ########################################
topics:
  - topic: modeling
    title: Animating in Maya
    layout: topic
    submission_link: 
    comments_enabled:
    published: true
    assigned: 1/26/2016
    due: 1/28/2016
#lessons  ########################################
course:
  unit:
    lessons:
      - lesson: maya-modeling
        title: Modeling in Maya
        subtitle: testing config
        layout: lesson
        submission_link: 
        comments_enabled:
        published: true
        assigned: 1/26/2016
        due: 1/28/2016
      - lesson: maya-animation
        subtitle: testing config
        title: Texturing in Maya
        layout: lesson
        submission_link: 
        comments_enabled:
        published: true
        assigned: 1/26/2016
        due: 1/28/2016
